version: "3.7"

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=ihavealongpassword
    depends_on:
      - mongodb
    

  mongodb:
    image: mongo
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - /Users/cleer/Documents/Desenvolvimento/Node/OI/DOCKER/VOL/MongoDB:/data/db
